### ISSUE TITLE
slow login due to default settings in xinetd glftpd

### ISSUE THREAD

**Issue by aZRGaOmjIw** [jonathanbower/docker-glftpd#16]
-I <#>	Timeout in seconds for an ident-lookup, 0 disables ident
		lookups. Note that if you use tcpd, it will do an ident lookup independently from glFTPd.
		
-n <#>	Number of DNS retries, 0 disables DNS resolving.

/etc/xinetd.d/glftpd
current value:
server_args     = -l -i -o   -r /glftpd/ftp-data/glftpd.conf

needed value:
server_args     = -I 0 -n 0 -l -i -o   -r /glftpd/ftp-data/glftpd.conf

Thanks!

**Comment by ZarTek-Creole** [comment]
I believe that disabling "ident" (-l 0) is not advisable and should not be the default setting. This is because it serves as a security measure for glftpd. When all users have an ident, glftpd behaves as if the port is closed when the ident is not sent by the FTP client. This is crucial in preventing unauthorized access, for instance, from port scanners.

On the other hand, disabling DNS resolution (-n 0) can enhance security, and this adjustment may be more appropriate.

**Comment by jonathanbower** [comment]
> -I <#> Timeout in seconds for an ident-lookup, 0 disables ident lookups. Note that if you use tcpd, it will do an ident lookup independently from glFTPd.
> 
> -n <#> Number of DNS retries, 0 disables DNS resolving.
> 
> /etc/xinetd.d/glftpd current value: server_args = -l -i -o -r /glftpd/ftp-data/glftpd.conf
> 
> needed value: server_args = -I 0 -n 0 -l -i -o -r /glftpd/ftp-data/glftpd.conf
> 
> Thanks!

I've added parameter GL_SERVER_ARGS to override default configuration. You can use:

`-e GL_SERVER_ARGS="-I 0 -n 0 -l -i -o"`

**Comment by jonathanbower** [comment]
5251ca19b42e0ccec5915922f4dd96c1a1932ad7
